# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_delete_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=300)),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_reg.User')),
            ],
        ),
    ]
