# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='posted_by',
            field=models.CharField(max_length=45),
        ),
    ]
