# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0004_auto_20170127_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_reg.Quote')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='login_reg.Favorite'),
        ),
    ]
