# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0005_auto_20170127_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
