# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0006_quote_quoted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quote_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='alias',
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='login_reg.Quote'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
