# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0008_auto_20170131_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quotes',
        ),
        migrations.AddField(
            model_name='quote',
            name='followers',
            field=models.ManyToManyField(to='login_reg.User'),
        ),
    ]
